# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_programm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(364, 156)
        self.lineEdit_files_folder = QtWidgets.QLineEdit(Form)
        self.lineEdit_files_folder.setGeometry(QtCore.QRect(20, 40, 251, 20))
        self.lineEdit_files_folder.setObjectName("lineEdit_files_folder")
        self.lineEdit_for_diode = QtWidgets.QLineEdit(Form)
        self.lineEdit_for_diode.setGeometry(QtCore.QRect(20, 100, 251, 20))
        self.lineEdit_for_diode.setObjectName("lineEdit_for_diode")
        self.label_diode = QtWidgets.QLabel(Form)
        self.label_diode.setGeometry(QtCore.QRect(20, 70, 141, 16))
        self.label_diode.setObjectName("label_diode")
        self.pushButton_files_folder = QtWidgets.QPushButton(Form)
        self.pushButton_files_folder.setGeometry(QtCore.QRect(280, 40, 75, 23))
        self.pushButton_files_folder.setObjectName("pushButton_files_folder")
        self.pushButton_diode = QtWidgets.QPushButton(Form)
        self.pushButton_diode.setGeometry(QtCore.QRect(280, 100, 75, 23))
        self.pushButton_diode.setObjectName("pushButton_diode")
        self.label_files_folder = QtWidgets.QLabel(Form)
        self.label_files_folder.setGeometry(QtCore.QRect(20, 10, 211, 16))
        self.label_files_folder.setObjectName("label_files_folder")
        self.pushButton_start = QtWidgets.QPushButton(Form)
        self.pushButton_start.setGeometry(QtCore.QRect(10, 130, 75, 23))
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_stop = QtWidgets.QPushButton(Form)
        self.pushButton_stop.setGeometry(QtCore.QRect(100, 130, 75, 23))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.label_timer = QtWidgets.QLabel(Form)
        self.label_timer.setGeometry(QtCore.QRect(270, 130, 91, 20))
        self.label_timer.setText("")
        self.label_timer.setObjectName("label_timer")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(180, 130, 91, 21))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_diode.setText(_translate("Form", "Путь до папки для диода"))
        self.pushButton_files_folder.setText(_translate("Form", "Выбрать"))
        self.pushButton_diode.setText(_translate("Form", "Выбрать"))
        self.label_files_folder.setText(_translate("Form", "Путь до папки с файлами"))
        self.pushButton_start.setText(_translate("Form", "Старт"))
        self.pushButton_stop.setText(_translate("Form", "Стоп"))
        self.label.setText(_translate("Form", "Прошло времени:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
