# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second_programm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(364, 224)
        self.lineEdit_input_folder = QtWidgets.QLineEdit(Form)
        self.lineEdit_input_folder.setGeometry(QtCore.QRect(20, 40, 251, 20))
        self.lineEdit_input_folder.setObjectName("lineEdit_input_folder")
        self.lineEdit_for_compare = QtWidgets.QLineEdit(Form)
        self.lineEdit_for_compare.setGeometry(QtCore.QRect(20, 100, 251, 20))
        self.lineEdit_for_compare.setObjectName("lineEdit_for_compare")
        self.label_compare = QtWidgets.QLabel(Form)
        self.label_compare.setGeometry(QtCore.QRect(20, 70, 221, 16))
        self.label_compare.setObjectName("label_compare")
        self.pushButton_input_folder = QtWidgets.QPushButton(Form)
        self.pushButton_input_folder.setGeometry(QtCore.QRect(280, 40, 75, 23))
        self.pushButton_input_folder.setObjectName("pushButton_input_folder")
        self.pushButton_compare = QtWidgets.QPushButton(Form)
        self.pushButton_compare.setGeometry(QtCore.QRect(280, 100, 75, 23))
        self.pushButton_compare.setObjectName("pushButton_compare")
        self.label_input_folder = QtWidgets.QLabel(Form)
        self.label_input_folder.setGeometry(QtCore.QRect(20, 10, 211, 16))
        self.label_input_folder.setObjectName("label_input_folder")
        self.pushButton_start = QtWidgets.QPushButton(Form)
        self.pushButton_start.setGeometry(QtCore.QRect(10, 190, 75, 23))
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_stop = QtWidgets.QPushButton(Form)
        self.pushButton_stop.setGeometry(QtCore.QRect(100, 190, 75, 23))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.label_timer = QtWidgets.QLabel(Form)
        self.label_timer.setGeometry(QtCore.QRect(270, 190, 91, 20))
        self.label_timer.setText("")
        self.label_timer.setObjectName("label_timer")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(180, 190, 91, 21))
        self.label.setObjectName("label")
        self.lineEdit_standart = QtWidgets.QLineEdit(Form)
        self.lineEdit_standart.setGeometry(QtCore.QRect(20, 160, 251, 20))
        self.lineEdit_standart.setObjectName("lineEdit_standart")
        self.pushButton_standart = QtWidgets.QPushButton(Form)
        self.pushButton_standart.setGeometry(QtCore.QRect(280, 160, 75, 23))
        self.pushButton_standart.setObjectName("pushButton_standart")
        self.label_standart = QtWidgets.QLabel(Form)
        self.label_standart.setGeometry(QtCore.QRect(20, 130, 221, 16))
        self.label_standart.setObjectName("label_standart")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_compare.setText(_translate("Form", "Путь до папки для сравнения"))
        self.pushButton_input_folder.setText(_translate("Form", "Выбрать"))
        self.pushButton_compare.setText(_translate("Form", "Выбрать"))
        self.label_input_folder.setText(_translate("Form", "Путь до папки с принятыми файлами"))
        self.pushButton_start.setText(_translate("Form", "Старт"))
        self.pushButton_stop.setText(_translate("Form", "Стоп"))
        self.label.setText(_translate("Form", "Прошло времени:"))
        self.pushButton_standart.setText(_translate("Form", "Выбрать"))
        self.label_standart.setText(_translate("Form", "Путь до папки с эталонными файлами"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
